### ISSUE TITLE
problems with the lineages.csv.gz

### ISSUE THREAD

**Issue by 65degnorth** [zyxue/ncbitax2lin#1]
the lineages.csv.gz file cannot be unzipped (using gunzip).  Is there obvious reason why this would fail (I have tried on Mac and Unix, and downloading Google Chrome, Safari) - and is it possible to get a link to the unzipped version of the lineages.csv files?  It'd save a huge amount of time as PANDAS is not installed on my computer or the remote server that I access.  Many thanks.

**Comment by zyxue** [comment]
Can you please show the error?

**Comment by zyxue** [comment]
It could be a git lfs error. FYI, https://github.com/git-lfs/git-lfs/issues/1486

I have removed `lineages.csv.gz` from git lfs. You should be able to download it again, and see. The ungzipped version is significantly larger.

**Comment by 65degnorth** [comment]
Good morning,


I am sorry - I wasn't more helpful (it was late and a child threw up on me...)


When I try to unzip the file by double clicking on it in Mac OSX (10.9.5) it converts it to .cpgz extension.  If I run 'gunzip' in the Terminal, then I get "gunzip: lineages.csv.gz: not in gzip format".  (As expected) unzip does not work"

Archive:  lineages.csv.gz

  End-of-central-directory signature not found.  Either this file is not

  a zipfile, or it constitutes one disk of a multi-part archive.  In the

  latter case the central directory and zipfile comment will be found on

  the last disk(s) of this archive.

note:  lineages.csv.gz may be a plain executable, not an archive

unzip:  cannot find zipfile directory in one of lineages.csv.gz or

        lineages.csv.gz.zip, and cannot find lineages.csv.gz.ZIP, period.

".  I have also failed to unpack the lineages.csv.gz file on a remote UNIX server.


Best wishes,


Phill



________________________________

**Comment by 65degnorth** [comment]
That worked a treat - thank you.

I am sorry - I wasn't more helpful (it was late and a child threw up on me...)

I was sorry not to provide more information before - but all that happened was that when I ran 'gunzip' in the Terminal, then I received "gunzip: lineages.csv.gz: not in gzip format".  

Many thanks again, 

P

**Comment by zyxue** [comment]
No worries. Glad it works now. Thank you for reporting. Otherwise I wouldn't know git lfs sometimes breaks.
