### ISSUE TITLE
Could not find a version that satisfies the requirement 

### ISSUE THREAD

**Issue by ParthKRaval** [zyxue/ncbitax2lin#24]
Hii! I  am trying to install this package, but I get error: Could not find a version that satisfies the requirement 
I am using PIP 21.3.1
Could you please help me with the latest version?
thanks,
Parth

**Comment by zyxue** [comment]
Can you paste the whole error?

**Comment by ParthKRaval** [comment]
Thanks for a prompt response, here is the full error:

ERROR: Could not find a version that satisfies the requirement ncbitax2lin (from versions: none)
ERROR: No matching distribution found for ncbitax2lin

**Comment by zyxue** [comment]
what python version are you on?
