### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by lfaino** [zyxue/ncbitax2lin#4]
Hi Developer,
i get this error when itry to install the tool:

```
lfaino@LabReverberi_PT /data/software $ git clone git@github.com:zyxue/ncbitax2lin.git
Cloning into 'ncbitax2lin'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```
Please make sure you have the correct access rights
and the repository exists.

I even try using sudo

can you help, please?

Cheers
Luigi

**Comment by alienzj** [comment]
Please using https:
```bash
git clone https://github.com/zyxue/ncbitax2lin.git
```

**Comment by zyxue** [comment]
@lfaino, I think your problem might be related to ssh key setup, https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/. If you prefer git protocol over https, try that and let me know. Thank you.
