### ISSUE TITLE
conda create env fails due to package versions

### ISSUE THREAD

**Issue by splaisan** [zyxue/ncbitax2lin#7]
At least on my ubuntu machine, env-conda.txt is not making conda create env happy (version numbers for 4 packages (mkl numpy readline tk).

After removing the version number for these 4 packages in env-conda.txt I could build the env, activate it, and run 'make'

hope this helps others.

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
mkl
numpy
openssl=1.0.2k=0
pandas=0.19.2=np112py27_1
pip=9.0.1=py27_1
python=2.7.13=0
python-dateutil=2.6.0=py27_0
pytz=2016.10=py27_0
readline
setuptools=27.2.0=py27_0
six=1.10.0=py27_0
sqlite=3.13.0=0
tk
wheel=0.29.0=py27_0
zlib=1.2.8=3
```

**Comment by zyxue** [comment]
An alternative: `conda create -y -p venv python=2 pandas`

The packaging is outdated, should've supported python3, any pull request is welcome.
